stages:
  - build
  - test
  - deploy
  - trigger_checkly

image: curlimages/curl

build:
  stage: build
  script:
    - echo "Building..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying..."

run_checkly:
  stage: trigger_checkly
  script:
    - echo "Deployment finished."
    # Call Checkly trigger
    - curl "https://api-test.checklyhq.com/check-groups/4/trigger/$CHECKLY_TOKEN" > $PWD/checkly.json
    # Exit with an error status if we find more than 0 "hasFailures: true" in the output
    - if [ $(grep -c '"hasFailures":true' $PWD/checkly.json) -ne 0 ]; then exit 1; fi
