language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules    
script:
  - npm run test:unit
  - npm run build  
before_deploy: "echo 'Deploying.'"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: checkly-ci-test
  skip_cleanup: true
  local_dir: dist 
after_deploy: 
  - "echo 'Deployment finished.'"
    # Call Checkly trigger
  - curl "https://api-test.checklyhq.com/check-groups/4/trigger/$CHECKLY_TOKEN" > $PWD/checkly.json
  # Exit with an error status if we find more than 0 "hasFailures: true" in the output
  - if [ $(grep -c '"hasFailures":true' $PWD/checkly.json) -ne 0 ]; then exit 1; fi